### ISSUE TITLE
Issues with DoNotKnow/CustomEntity

### ISSUE THREAD

**Issue by AlertingAvian** [AlertingAvian/DoNotKnow#1]
Sprite does not work, causes map loading failure, it is actually creating an instance of it which is further than I got previously.

New Instance of CustomEntity
`(07/08/2022 01:39:22) [Everest] [Info] [DoNotKnow] Added instance of CustomEntity`

Error
`System.Exception: Missing animation name in SpriteData: 'Graphics/DoNotKnowSpriteBank.xml'!`

Line that causes error (CustomEntity.cs)
`GFX.SpriteBank.Create("Graphics/DoNotKnowSpriteBank.xml");`

**Comment by AlertingAvian** [comment]
There is probably also an issue with how I have the graphics organized but idk

**Comment by CaptainCarpensir** [comment]
hahaha i fixed it nerd, close your issue
